### PR TITLE
Added javadoc task and updated gradle version

### PR DESCRIPTION
**Pull request by lyze237**
Follow-up PR to add the javadoc task to the build and also update the gradle wrapper.

### CODE REVIEW

**Review by tommyettinger — APPROVED** [review]
Looks good to me! Having docs is good for sure.

**Comment by lyze237** [comment]
We could publish javadoc to github pages if we want to. Up to @fxgaming though.

Example: https://github.com/lyze237/gdx-TinyVG - https://lyze237.github.io/gdx-TinyVG/

**Comment by bonenaut7** [comment]
damn thanks lol, feeling like a kid who getting help from grown-ups

**Comment by tommyettinger** [comment]
I feel the same way whenever mgsx corrects my OpenGL code, heh.

**Pull request merged**
